### PR TITLE
Handle hdfs_namenode_principal properly and refactor auto configuration logic

### PR DESCRIPTION
**Pull request by garthcn**
This is related to this issue: https://github.com/spotify/snakebite/issues/175

See this comment: https://github.com/spotify/snakebite/issues/175#issuecomment-185966102

This might not be the ideal way since removing the side effects [here](https://github.com/spotify/snakebite/blob/master/snakebite/config.py#L94) and [here] (https://github.com/spotify/snakebite/blob/master/snakebite/config.py#L90) might be a better solution. 

Let me know if this pull request makes sense and really appreciate your great work on the library!

### CODE REVIEW

**Comment by garthcn** [comment]
More detailed description: 

The problem: https://github.com/spotify/snakebite/issues/175#issuecomment-185966102

Changes in the PR: 

1. Remove class variables in `HDFSConfig`. Calling `get_external_config()` will return a dict like this:     

    ```
    {
        namenodes: [{'namenodes': <host>, 'port': 1234}],
        use_trash: True,
        use_sasl: True,
        hdfs_namenode_principal: <principal>
    }
    ```
2. In places where the class variables in `HDFSConfig` were referenced, call  `get_external_config()` and use the values returned in the dict. 

3. In `Client`, `HAClient`, add the option to pass in `hdfs_namenode_principal`. `AutoConfigClient` will call `get_external_config()` and pass `hdfs_namenode_principal` to `HAClient`. 

4. In `SocketRpcChannel`, `SaslRpcClient` and `RpcService`, change `__init__` to accept the `hdfs_namenode_principal` which will be passed down the chain from `Client` or `HAClient`. 

5. Update test cases to reflect the change

**Comment by wouterdebie** [comment]
I'll talk to @ravwojdyla tomorrow, but LGTM for now.

**Comment by wouterdebie** [comment]
Would you be able to squash this commit?

**Comment by garthcn** [comment]
@wouterdebie I just squashed the commits into one. Let me know if you have any comments/feedback. Thanks!

**Comment by ravwojdyla** [comment]
We eventually want to refactor the way we handle config/ctor, but that is out of the scope of this bug/PR. Thanks @garthcn for great investigation and patch. lgtm.

**Pull request merged**
