### PR TITLE
Add SASL authentication

### PR DESCRIPTION
**Pull request by bolkedebruin**
This patch implements SASL authentication (only GSSAPI was tested). SASL authentication is required for secure clusters, specifically the ones that use Kerberos. In Hadoop SASL is implemented on top of the Hadoop RPC protocol. I have chosen not to refactor any of the code yet, that could be done in a later patch.

* Dependencies on sasl and python-krbV are added

### CODE REVIEW

**Comment by bolkedebruin** [comment]
I am looking for some feedback on this. It fixes issue #59 for Kerberos support.

**Comment by wouterdebie** [comment]
Just reviewed this PR and I'm +1, just want @ravwojdyla to +1 too, since this is quite a big thing.

Thanks a million for implementing this!

**Comment by chenbensong** [comment]
Hello, the Kerberos support is great! In our environment we also enabled HDFS encrypted transport (rpc-protection is set to "privacy"). Seems like only unencrypted RPC responses are supported for now? I saw serverdefaults() in client.py reads encryptDataTransfer info but did not use it. Is it possible to add the rpc encrypt support? What work will be involved to make it happen? Thanks in advance!

**Comment by bolkedebruin** [comment]
@chenbensong a bit of work needs to happen. The good news is that it is not as large as the initial commit (I think!). The messages need to be wrapped and unwrapped within the (kerberos)client. The bad news is that I don't have a cluster to test it out. I don't mind trying it out however I do like to have this patch reviewed and landed first. @ravwojdyla would you mind taking a look?

**Comment by chenbensong** [comment]
@bolkedebruin Thanks for the explanations! Yes this patch itself is substantial and should land first.

**Comment by krise3k** [comment]
+1

**Comment by garthcn** [comment]
:+1:

**Comment by ssorokin** [comment]
+1, we're excited about Kerberos support as well - when are you guys planning to merge?

**Comment by kerzhner** [comment]
:+1: Any way to get this PR merged in?

**Comment by artemyudin** [comment]
This is exactly what we need. Super stocked about Kerberos support! Any timeline projections on when we can expect this to get merged? :+1:

**Comment by drhops** [comment]
Excited for this! Can we merge? :+1:

**Comment by wouterdebie** [comment]
Here we go! Seems all test pass, so I'm good :)

**Pull request merged**
