### PR TITLE
Do conditional import higher up to make sure import stays in scope

### PR DESCRIPTION
**Pull request by bolkedebruin**
This fixes issue-#174 while keeping a conditional import

### CODE REVIEW

**Comment by bolkedebruin** [comment]
@wouterdebie @ravwojdyla if you have the time please check and merge this as now kerberos authentication is blocked by this issue.

**Comment by ravwojdyla** [comment]
Thanks @bolkedebruin for your contributions! I would maybe rename the global variable to internal notation `_kerberos_available` (do you agree?). Otherwise looks good.

We really need to create some kerberos testing env.

**Comment by bolkedebruin** [comment]
@ravwojdyla agreed and fixed.

Love the have kerberos testing. I am doing some research on it, but it is not pulled off easily. Does travis support docker-on-docker?

**Comment by wouterdebie** [comment]
Sorry to nit-pick, but could you squash this commit?

**Comment by bolkedebruin** [comment]
@wouterdebie np. Done.

**Pull request merged**
